config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:new, :show, :create] do
    post :rematch, on: :member
    resources :moves, only: :create
  end

  root 'games#new'
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id               :integer          not null, primary key
#  name             :string
#  rows_size        :integer
#  columns_size     :integer
#  winning_row_size :integer
#  active_player_id :integer
#  winner_id        :integer
#  completed        :boolean          default(FALSE), not null
#  winner_row       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Game < ActiveRecord::Base
  serialize :winner_row, Array

  has_many :players
  has_many :moves, through: :players
  has_one :winner, class_name: 'Player'
  belongs_to :active_player, class_name: 'Player'

  accepts_nested_attributes_for :players
  after_create :assign_active_player

  def console_game
    return @console_game if @console_game

    @console_game = NoughtsAndCrosses::Game.new(rows_size, columns_size, winning_row_size)
    players.each { |player| @console_game.add_player(player.console_player) }
    @console_game.prepare
    @console_game
  end

  def update_stage!
    replay_moves_on_console
    set_completion_or_pass_turn!
  end

  def replay_moves_on_console
    moves.each do |move|
      cell = console_game.cell_at(move.row, move.column)
      console_game.occupy(cell, move.token)
      console_game.pass_turn
    end
  end

  def clone_with_the_same_setup
    game = self.class.new(rows_size: rows_size, columns_size: columns_size, winning_row_size: winning_row_size)
    players.each { |player| game.players << Player.new(strategy: player.strategy, token: player.token) }
    game.save!
    game
  end

  private

  def assign_active_player
    self.active_player = players.find_by(token: console_game.active_player.token)
    save!
  end

  def set_completion_or_pass_turn!
    if console_game.game_over?
      winner_id = active_player.id unless console_game.draw?
      update_attributes!(completed: true, winner_row: console_game.winner_row, winner_id: winner_id)
    else
      self.active_player = players.find_by(token: console_game.active_player.token) if console_game.active_player
      save!
    end
  end
end

app/models/move.rb
# == Schema Information
#
# Table name: moves
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  row        :integer
#  column     :integer
#  token      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Move < ActiveRecord::Base
  belongs_to :player
  validates :row, :column, :token, presence: true
  validate :uniq_coordinates

  private

  def uniq_coordinates
    duplicate = player.game.moves.find_by(row: row, column: column)
    errors.add(:base, 'Duplicate') if duplicate
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  strategy   :string
#  token      :string
#  game_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Player < ActiveRecord::Base
  belongs_to :game
  has_many :moves

  STRATEGIES_MAPPING = [
    { title: 'Human', class: NoughtsAndCrosses::Player::Human },
    { title: 'AI: expert', class: NoughtsAndCrosses::Player::AI::WinBlockOrOptimal },
    { title: 'AI: random',  class: NoughtsAndCrosses::Player::AI::Random }
  ]

  def human?
    console_player_class == NoughtsAndCrosses::Player::Human
  end

  def console_player_class
    STRATEGIES_MAPPING.find { |m| m[:title] == strategy }[:class]
  end

  def console_player
    console_player_class.new(token)
  end

  def do_the_move(move_params)
    if human?
      moves.create!(move_params)
      game.replay_moves_on_console
    else
      make_move
    end
  end

  def make_move
    game.replay_moves_on_console
    cell = game.console_game.active_player.make_move
    moves.create!(row: cell.row, column: cell.column, token: cell.token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :load_game, only: [:show, :rematch]

  def show
    gon.game = @game.as_json(include: :active_player)
  end

  def new
    @game = Game.new(rows_size: 3, columns_size: 3, winning_row_size: 3)
    @game.players = [Player.new(token: 'x'), Player.new(token: 'o')]
  end

  def create
    game = Game.create!(game_params)
    redirect_to game_path(game)
  end

  def rematch
    new_game = @game.clone_with_the_same_setup
    redirect_to game_path(new_game)
  end

  protected

  def load_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:rows_size, :columns_size, :winning_row_size, players_attributes: [:token, :strategy])
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_filter :load_game, only: :create

  def create
    move = create_move
    update_stage
    render json: { game: @game.as_json(include: :active_player), move: move }, status: 201
  end

  protected

  def move_params
    params.fetch(:move, {}).permit(:row, :column, :token)
  end

  def load_game
    @game = Game.find(params[:game_id])
  end

  def update_stage
    @game.update_stage!
  end

  def create_move
    @game.active_player.do_the_move(move_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def player_strategies_options
    Player::STRATEGIES_MAPPING.map { |m| m[:title] }
  end

  def cell_inline_styles
    "width: #{cell_width(@game)}% !important;"
  end

  def cell_width(game)
    80 / game.columns_size
  end

  def board_for(game)
    game.replay_moves_on_console
    game.console_game.board.map do |row|
      row.map do |cell|
        { row: cell.row, column: cell.column, token: cell.token }
      end
    end
  end
end

app/views/games/new.html.haml
.row.top-buffer
  = form_for @game, html: { class: 'form-horizontal' } do |f|
    .form-group
      .col-xs-2.col-xs-offset-4
        = f.label :rows_size, 'Rows', class: 'control-label'
      .col-xs-2
        = f.number_field :rows_size, within: (3..10), class: 'form-control'
    .form-group
      .col-xs-2.col-xs-offset-4
        = f.label :columns_size, 'Columns', class: 'control-label'
      .col-xs-2
        = f.number_field :columns_size, within: (3..10), class: 'form-control'
    .form-group
      .col-xs-2.col-xs-offset-4
        = f.label :winning_row_size, 'Winning streak', class: 'control-label'
      .col-xs-2
        = f.number_field :winning_row_size, within: (3..10), class: 'form-control'

    .col-xs-8.col-xs-offset-2
      %hr

    = f.fields_for :players do |fp|
      .form-group
        .col-xs-2.col-xs-offset-2
          = fp.label :token, class: 'control-label'
        .col-xs-2
          = fp.text_field :token, readonly: true, class: 'form-control'
        .col-xs-2
          = fp.label :strategy, class: 'control-label col-xs-1'
        .col-xs-2
          = fp.select :strategy, player_strategies_options, {}, class: 'form-control'

    .form-group.top-buffer
      = f.submit 'Start game', class: 'btn btn-primary col-xs-8 col-xs-offset-2'

app/views/games/show.html.haml
.row.top-buffer
  .col-xs-8.col-xs-offset-2
    %table.table.board
      %tbody
        - board_for(@game).each do |row|
          %tr.row
            - row.each do |cell|
              %td.cell.col.col-xs-1{ data: { row: cell[:row], column: cell[:column], token: cell[:token] }, style: cell_inline_styles }

.row
  .col-xs-2.col-xs-offset-4
    = link_to 'Rematch', rematch_game_path(@game), method: :post, class: 'action-rematch'
  .col-xs-6
    = link_to 'New game', new_game_path, class: 'action-new'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Naughts And Crosses: play hot seat, face a bot or watch bots playing :)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = requirejs_include_tag  'application'
    = csrf_meta_tags
    = Gon::Base.render_data({})
  %body
    .container
      = yield